# Variabelen
kleuren_legers = {
    "blauw": "#71baf6",
    "geel": "#f5d953",
    "groen": "#588c60",
    "oranje": "#df7d41",
    "paars": "#7f638c",
    "rood": "#ef3740",
}

landen = (
    {
        'Alaska': {'continent': 'N_Amerika', 'troep': 'I', 'locatie': '(105, 120)', 'grenzen': ['Noordwestelijke staten', 'Alberta', 'Kamtsjatka'], 'speler': 'blauw', 'aantal_troepen': 1},
        'Peru': {'continent': 'Z_Amerika', 'troep': 'I', 'locatie': '(309, 508)', 'grenzen': ['Venezuela', 'Brazilie', 'Argentinie'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'Argentinie': {'continent': 'Z_Amerika', 'troep': 'I', 'locatie': '(334, 596)', 'grenzen': ['Peru', 'Brazilie'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'Scandinavie': {'continent': 'Europa', 'troep': 'C', 'locatie': '(588, 163)', 'grenzen': ['Ijsland', 'Rusland', 'Groot-brittannie', 'Noord-europa'], 'speler': 'blauw', 'aantal_troepen': 1},
        'Rusland': {'continent': 'Europa', 'troep': 'C', 'locatie': '(684, 217)', 'grenzen': ['Scandinavie', 'Noord-europa', 'Zuid-europa', 'Oeral', 'Afghanistan', 'Midden-oosten'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'Groot-brittannie': {'continent': 'Europa', 'troep': 'A', 'locatie': '(495, 255)', 'grenzen': ['Ijsland', 'Scandinavie', 'Noord-europa', 'West-europa'], 'speler': 'blauw', 'aantal_troepen': 1},
        'Zuid-europa': {'continent': 'Europa', 'troep': 'A', 'locatie': '(599, 326)', 'grenzen': ['Noord-europa', 'West-europa', 'Rusland', 'Midden-oosten', 'Noord-afrika', 'Egypte'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'Egypte': {'continent': 'Afrika', 'troep': 'I', 'locatie': '(631, 438)', 'grenzen': ['Noord-afrika', 'Zuid-europa', 'Midden-oosten', 'Oost-afrika'], 'speler': 'blauw', 'aantal_troepen': 1},
        'Siberie': {'continent': 'Azie', 'troep': 'C', 'locatie': '(849, 143)', 'grenzen': ['Oeral', 'China', 'Yakutsk', 'Irkoetsk', 'Mongolie'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'Afghanistan': {'continent': 'Azie', 'troep': 'C', 'locatie': '(774, 283)', 'grenzen': ['Rusland', 'Midden-oosten', 'Oeral', 'China', 'India'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'Japan': {'continent': 'Azie', 'troep': 'A', 'locatie': '(1039, 277)', 'grenzen': ['Mongolie', 'Kamtsjatka'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'Midden-oosten': {'continent': 'Azie', 'troep': 'I', 'locatie': '(707, 394)', 'grenzen': ['Zuid-europa', 'Rusland', 'Afghanistan', 'India', 'Egypte', 'Oost-afrika'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'India': {'continent': 'Azie', 'troep': 'C', 'locatie': '(835, 390)', 'grenzen': ['Midden-oosten', 'Afghanistan', 'China', 'Zuidoost-azie'], 'speler': 'blauw', 'aantal_troepen': 1}, 
        'West-australie': {'continent': 'Oceanie', 'troep': 'A', 'locatie': '(975, 637)', 'grenzen': ['Indonesie', 'Oost-australie'], 'speler': 'blauw', 'aantal_troepen': 1}, 
    },
    {
        'Noordwestelijke staten': {'continent': 'N_Amerika', 'troep': 'A', 'locatie': '(217, 121)', 'grenzen': ['Alaska', 'Alberta', 'Ontario', 'Groenland'], 'speler': 'groen', 'aantal_troepen': 1},
        'Groenland': {'continent': 'N_Amerika', 'troep': 'C', 'locatie': '(417, 86)', 'grenzen': ['Noordwestelijke staten', 'Ontario', 'Oost-canada', 'Ijsland'], 'speler': 'groen', 'aantal_troepen': 1},  
        'Ontario': {'continent': 'N_Amerika', 'troep': 'C', 'locatie': '(280, 196)', 'grenzen': ['Noordwestelijke staten', 'Alberta', 'Groenland', 'Verenigde staten (west)', 'Oost-canada', 'Verenigde staten (oost)'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Verenigde staten (west)': {'continent': 'N_Amerika', 'troep': 'A', 'locatie': '(215, 270)', 'grenzen': ['Alberta', 'Ontario', 'Verenigde staten (oost)', 'Centraal-amerika'], 'speler': 'groen', 'aantal_troepen': 1},
        'Verenigde staten (oost)': {'continent': 'N_Amerika', 'troep': 'A', 'locatie': '(296, 284)', 'grenzen': ['Verenigde staten (west)', 'Ontario', 'Oost-canada', 'Centraal-amerika'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Brazilie': {'continent': 'Z_Amerika', 'troep': 'A', 'locatie': '(382, 483)', 'grenzen': ['Venezuela', 'Peru', 'Argentinie', 'Noord-afrika'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Ijsland': {'continent': 'Europa', 'troep': 'I', 'locatie': '(511, 169)', 'grenzen': ['Groenland', 'Groot-brittannie', 'Scandinavie'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Noord-afrika': {'continent': 'Afrika', 'troep': 'C', 'locatie': '(568, 465)', 'grenzen': ['Brazilie', 'West-europa', 'Zuid-europa', 'Egypte', 'Centraal-afrika', 'Oost-afrika'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Oost-afrika': {'continent': 'Afrika', 'troep': 'I', 'locatie': '(680, 500)', 'grenzen': ['Noord-afrika', 'Egypte', 'Centraal-afrika', 'Midden-oosten', 'Zuid-afrika', 'Madagaskar'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Madagaskar': {'continent': 'Afrika', 'troep': 'C', 'locatie': '(729, 641)', 'grenzen': ['Zuid-afrika', 'Oost-afrika'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Kamtsjatka': {'continent': 'Azie', 'troep': 'I', 'locatie': '(1024, 116)', 'grenzen': ['Yakutsk', 'Irkoetsk', 'Mongolie', 'Japan', 'Alaska'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Irkoetsk': {'continent': 'Azie', 'troep': 'C', 'locatie': '(919, 195)', 'grenzen': ['Siberie', 'Yakutsk', 'Kamtsjatka', 'Mongolie'], 'speler': 'groen', 'aantal_troepen': 1},
        'Indonesie': {'continent': 'Oceanie', 'troep': 'A', 'locatie': '(931, 540)', 'grenzen': ['Zuidoost-azie', 'Nieuw-guinea', 'West-australie'], 'speler': 'groen', 'aantal_troepen': 1}, 
        'Oost-australie': {'continent': 'Oceanie', 'troep': 'A', 'locatie': '(1052, 612)', 'grenzen': ['Nieuw-guinea', 'West-australie'], 'speler': 'groen', 'aantal_troepen': 1}, 
    },
    {
        'Alberta': {'continent': 'N_Amerika', 'troep': 'C', 'locatie': '(201, 187)', 'grenzen': ['Alaska', 'Noordwestelijke staten', 'Ontario', 'Verenigde staten (west)'], 'speler': 'paars', 'aantal_troepen': 1},
        'Oost-canada': {'continent': 'N_Amerika', 'troep': 'C', 'locatie': '(355, 204)', 'grenzen': ['Groenland', 'Ontario', 'Verenigde staten (oost)'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Centraal-amerika': {'continent': 'N_Amerika', 'troep': 'A', 'locatie': '(222, 350)', 'grenzen': ['Verenigde staten (west)', 'Verenigde staten (oost)', 'Venezuela'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Venezuela': {'continent': 'Z_Amerika', 'troep': 'I', 'locatie': '(303, 422)', 'grenzen': ['Centraal-amerika', 'Peru', 'Brazilie'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Noord-europa': {'continent': 'Europa', 'troep': 'A', 'locatie': '(587, 262)', 'grenzen': ['Groot-brittannie', 'Scandinavie', 'Rusland', 'West-europa', 'Zuid-europa'], 'speler': 'paars', 'aantal_troepen': 1},
        'West-europa': {'continent': 'Europa', 'troep': 'A', 'locatie': '(518, 343)', 'grenzen': ['Groot-brittannie', 'Noord-europa', 'Zuid-europa', 'Noord-afrika'], 'speler': 'paars', 'aantal_troepen': 1},
        'Centraal-afrika': {'continent': 'Afrika', 'troep': 'I', 'locatie': '(626, 550)', 'grenzen': ['Noord-afrika', 'Oost-afrika', 'Zuid-afrika', 'Madagaskar'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Zuid-afrika': {'continent': 'Afrika', 'troep': 'A', 'locatie': '(639, 639)', 'grenzen': ['Centraal-afrika', 'Oost-afrika', 'Madagaskar'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Oeral': {'continent': 'Azie', 'troep': 'C', 'locatie': '(794, 190)', 'grenzen': ['Rusland', 'Siberie', 'China', 'Afghanistan'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Yakutsk': {'continent': 'Azie', 'troep': 'C', 'locatie': '(931, 111)', 'grenzen': ['Siberie', 'Kamtsjatka', 'Irkoetsk'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'China': {'continent': 'Azie', 'troep': 'I', 'locatie': '(890, 332)', 'grenzen': ['Oeral', 'Siberie', 'Mongolie', 'India', 'Zuidoost-azie', 'Afghanistan'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Mongolie': {'continent': 'Azie', 'troep': 'I', 'locatie': '(932, 274)', 'grenzen': ['Siberie', 'Irkoetsk', 'Japan', 'China'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Zuidoost-azie': {'continent': 'Azie', 'troep': 'I', 'locatie': '(919, 425)', 'grenzen': ['India', 'China', 'Zuidoost-azie', 'Indonesie'], 'speler': 'paars', 'aantal_troepen': 1}, 
        'Nieuw-guinea': {'continent': 'Oceanie', 'troep': 'I', 'locatie': '(1021, 511)', 'grenzen': ['Indonesie', 'Oost-australie'], 'speler': 'paars', 'aantal_troepen': 1}, 
    }
)